# Generated by Django 5.0.6 on 2024-06-15 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerorder',
            name='time_canceled',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='customerorder',
            name='time_completed',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='customerorder',
            name='time_paid',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
